NOISSUE - Fix disconnect things
mainflux/sdk-py pull request #7
Opened 2022-01-07 16:10 UTC by 0x6f736f646f

Signed-off-by: 0x6f736f646f <blackd0t@protonmail.com>

### What does this do?
It fixes the disconnect thing function

### Which issue(s) does this PR fix/relate to?
It doesn't relate to previous issues

### List any changes that modify/break current functionality
There was no disconnect things function as indicated by the docs [here](https://docs.mainflux.io/api/#disconnect)

### Have you included tests for your changes?
Yes.

### Did you document any new/modified functionality?
No

2022-01-07 17:09 UTC, drasko approved these changes
LGTM

2022-01-10 20:46 UTC, fbugarski requested changes

2022-01-10 20:46 UTC, fbugarski commented on lib/things.py
> +        return mf_resp
Add new line at the end of the file.

2022-01-11 15:38 UTC, 0x6f736f646f commented on lib/things.py
> +        return mf_resp
Added the new line

2022-01-11 15:40 UTC, fbugarski approved these changes
LGTM

2022-01-11 20:31 UTC, drasko approved these changes
LGTM

2022-01-11 20:31 UTC, merged